bdk:
  host: develop2.symphony.com
  bot:
    username: wdk-studio-bot
    privateKey:
      path: rsa/bot-privatekey.pem
workflows.folder: ../workflows
logging.level:
  org.reflections: error
  org.springframework: error
  org.apache: error
  com.zaxxer: error
  com.symphony: info
  # com.symphony.bdk.workflow.engine.camunda.bpmn.CamundaBpmnBuilder: debug
spring.main.web-application-type: none
management.endpoints.web.exposure.exclude: "*"
