bdk:
  host: develop2.symphony.com
  bot:
    username: wdk-studio-bot
    privateKey:
      path: rsa/bot-privatekey.pem
workflows.folder: ../workflows
logging.level:
  org.reflections: error
  org.springframework: error
  org.apache: error
  com.zaxxer: error
  com.symphony: info
  # com.symphony.bdk.workflow.engine.camunda.bpmn.CamundaBpmnBuilder: debug
management.endpoints.web.exposure.exclude: "*"
spring.datasource.url: jdbc:h2:file:../workflows/data;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
