bdk:
  host: develop2.symphony.com
  bot:
    username: wdk-studio-bot
    privateKey.path: rsa/bot-privatekey.pem
wdk:
  workflows.path: ""
  properties:
    monitoring-token: abc
    management-token: abc
logging.level:
  org:
    reflections: error
    springframework: error
    apache: error
  com:
    zaxxer: error
    symphony: info
    symphony.bdk:
      workflow:
        swadl: error
        engine.executor.DebugExecutor: debug
      spring.config: error
  springfox: error
spring:
  datasource:
    wdk:
      jdbc-url: jdbc:h2:file:./data/wdk;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    camunda:
      jdbc-url: jdbc:h2:file:./data/camunda;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
management:
  server.port: 8080
  endpoints.web.base-path: /
