# BDK Core Configuration
bdk:
  host: develop2.symphony.com
  app:
    appId: localhost-10443
    privateKey:
      path: rsa/privatekey.pem

# BDK App Configuration
bdk-app:
  auth:
    enabled: true
    jwt-cookie:
      enabled: true
      max-age: 1d
  cors:
    "[/**]":
      allowed-origins: "*"
      allowed-credentials: false
  tracing:
    enabled: true
    url-patterns:
      - /api/*

logging:
  pattern:
    # Added %clr(%X{X-Trace-Id}){magenta} to output the MDC traceId in logs
    console: '%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID}){magenta} %clr(%X{X-Trace-Id}){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx'
  level:
    com.symphony: debug

server:
  port: 10443
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: password
    key-store-type: pkcs12
    key-alias: tomcat

spring:
  main.banner-mode: off
