bdk:
  host: develop2.symphony.com
  app:
    appId: wdk-studio
    privateKey.path: rsa/app-privatekey.pem

bdk-app:
  auth:
    enabled: true
  cors:
    "[/**]":
      allowed-origins: "*"
      allowed-methods: [ "POST", "GET", "PUT", "DELETE" ]
      allowed-headers: "*"
      allowed-credentials: false

wdk.studio:
  base-uri: http://localhost:8080/wdk/v1
  github-token: abc
  monitoring-token: abc

logging.level:
  org:
    apache: error
    glassfish: error
    springframework:
      security: error
      web.servlet: error
      boot:
        web.servlet: error
        autoconfigure.web: error
        actuate: error
  com.symphony.bdk.app.spring.config: error

server.error.include-message: always
spring.main.banner-mode: off
management.endpoints.web.base-path: /
